use_frameworks!
platform :ios, '12.0'

target 'JHTAlertController_Example' do
  pod 'JHTAlertController', :path => '../'

  target 'JHTAlertController_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    myTargets = ['JHTAlertController']
    installer.pods_project.targets.each do |target|
        if myTargets.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
