use_frameworks!
platform :ios, '12.0'

target 'JHTAlertController_Example' do
  pod 'JHTAlertController', :path => '../'

  target 'JHTAlertController_Tests' do
    inherit! :search_paths

    
  end
end
